In [9]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [10]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [13]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  58130.9 
Prediction:
 [-53.86912537 -78.10269928 -69.77436829 -79.17436981 -60.33997345]
10 Cost:  30.8943 
Prediction:
 [ 159.33770752  178.1963501   182.74046326  195.81069946  135.15940857]
20 Cost:  30.2019 
Prediction:
 [ 159.96154785  178.9863739   183.4979248   196.63829041  135.76971436]
30 Cost:  30.0421 
Prediction:
 [ 159.94223022  179.00326538  183.49368286  196.63641357  135.79032898]
40 Cost:  29.8833 
Prediction:
 [ 159.92100525  179.01777649  183.48712158  196.63200378  135.80906677]
50 Cost:  29.7254 
Prediction:
 [ 159.89985657  179.03224182  183.48059082  196.62762451  135.82775879]
60 Cost:  29.5683 
Prediction:
 [ 159.87876892  179.04667664  183.47410583  196.62327576  135.84643555]
70 Cost:  29.4119 
Prediction:
 [ 159.85769653  179.06108093  183.46760559  196.618927    135.86502075]
80 Cost:  29.2565 
Prediction:
 [ 159.8367157   179.07540894  183.46110535  196.61456299  135.88357544]
90 Cost:  29.1018 
Prediction:
 [ 159.81578064  179.0897522   183.4546

800 Cost:  20.0124 
Prediction:
 [ 158.46470642  180.01351929  183.0375824   196.33250427  137.0941925 ]
810 Cost:  19.9075 
Prediction:
 [ 158.44744873  180.02532959  183.03224182  196.32897949  137.10939026]
820 Cost:  19.8035 
Prediction:
 [ 158.43028259  180.03709412  183.02694702  196.32546997  137.12454224]
830 Cost:  19.6998 
Prediction:
 [ 158.4131012   180.04881287  183.0216217   196.32197571  137.13963318]
840 Cost:  19.5968 
Prediction:
 [ 158.39601135  180.0605011   183.01634216  196.31848145  137.15470886]
850 Cost:  19.4943 
Prediction:
 [ 158.37893677  180.07217407  183.01107788  196.31500244  137.16973877]
860 Cost:  19.3924 
Prediction:
 [ 158.36192322  180.08380127  183.00582886  196.31155396  137.18470764]
870 Cost:  19.291 
Prediction:
 [ 158.34495544  180.09541321  183.00056458  196.30807495  137.19966125]
880 Cost:  19.1902 
Prediction:
 [ 158.32803345  180.10696411  182.99534607  196.30461121  137.21455383]
890 Cost:  19.0899 
Prediction:
 [ 158.31112671  180.118

1780 Cost:  12.024 
Prediction:
 [ 156.97665405  181.03038025  182.57739258  196.03208923  138.40124512]
1790 Cost:  11.9623 
Prediction:
 [ 156.96339417  181.03944397  182.57330322  196.02944946  138.41287231]
1800 Cost:  11.901 
Prediction:
 [ 156.95016479  181.04847717  182.56919861  196.02682495  138.42443848]
1810 Cost:  11.84 
Prediction:
 [ 156.93696594  181.0574646   182.56510925  196.02418518  138.43597412]
1820 Cost:  11.7793 
Prediction:
 [ 156.92382812  181.06646729  182.56105042  196.02157593  138.44747925]
1830 Cost:  11.719 
Prediction:
 [ 156.91070557  181.07540894  182.55697632  196.01896667  138.45896912]
1840 Cost:  11.6589 
Prediction:
 [ 156.89762878  181.08435059  182.55291748  196.01635742  138.47041321]
1850 Cost:  11.5993 
Prediction:
 [ 156.88458252  181.09326172  182.54888916  196.01376343  138.48182678]
1860 Cost:  11.5399 
Prediction:
 [ 156.87158203  181.10214233  182.54486084  196.01118469  138.4932251 ]
1870 Cost:  11.4808 
Prediction:
 [ 156.8585968   1