In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  29521.5 
Prediction:
 [[ -2.02283525]
 [-11.67909336]
 [ -6.31489611]
 [-11.96467686]
 [ -7.02916765]
 [-14.15564823]
 [-13.96064854]
 [-17.06279755]
 [-19.29862976]
 [-29.97728729]]
10 Cost:  128.269 
Prediction:
 [[ 159.30743408]
 [ 182.31710815]
 [ 184.78253174]
 [ 196.18795776]
 [ 140.92019653]
 [  94.98316193]
 [ 141.87219238]
 [  98.4920578 ]
 [ 162.06637573]
 [ 138.09213257]]
20 Cost:  116.425 
Prediction:
 [[ 160.35823059]
 [ 183.64086914]
 [ 186.05332947]
 [ 197.59855652]
 [ 141.92295837]
 [  95.77059174]
 [ 142.95056152]
 [  99.32113647]
 [ 163.35014343]
 [ 139.34541321]]
30 Cost:  115.306 
Prediction:
 [[ 160.32763672]
 [ 183.66433716]
 [ 186.04324341]
 [ 197.61401367]
 [ 141.93405151]
 [  95.82659912]
 [ 142.98452759]
 [  99.37587738]
 [ 163.41836548]
 [ 139.47242737]]
40 Cost:  114.261 
Prediction:
 [[ 160.28985596]
 [ 183.67892456]
 [ 186.02458191]
 [ 197.61999512]
 [ 141.93835449]
 [  95.87742615]
 [ 143.01133728]
 [  99.42515564]
 [ 163.47807312]
 [ 139.5912780

470 Cost:  77.4955 
Prediction:
 [[ 158.83222961]
 [ 184.22817993]
 [ 185.29527283]
 [ 197.85580444]
 [ 142.07940674]
 [  97.84017181]
 [ 144.07447815]
 [ 101.38468933]
 [ 165.78404236]
 [ 144.21026611]]
480 Cost:  76.8052 
Prediction:
 [[ 158.80194092]
 [ 184.23931885]
 [ 185.27996826]
 [ 197.86088562]
 [ 142.08175659]
 [  97.88105011]
 [ 144.09729004]
 [ 101.4267807 ]
 [ 165.83204651]
 [ 144.30708313]]
490 Cost:  76.1216 
Prediction:
 [[ 158.77180481]
 [ 184.25038147]
 [ 185.26472473]
 [ 197.86592102]
 [ 142.08409119]
 [  97.92167664]
 [ 144.12001038]
 [ 101.46870422]
 [ 165.87980652]
 [ 144.40341187]]
500 Cost:  75.4444 
Prediction:
 [[ 158.74177551]
 [ 184.26133728]
 [ 185.24951172]
 [ 197.8709259 ]
 [ 142.08634949]
 [  97.96212769]
 [ 144.1426239 ]
 [ 101.51047516]
 [ 165.92732239]
 [ 144.49928284]]
510 Cost:  74.7735 
Prediction:
 [[ 158.71195984]
 [ 184.27227783]
 [ 185.23442078]
 [ 197.87594604]
 [ 142.08862305]
 [  98.00238037]
 [ 144.16519165]
 [ 101.55210876]
 [ 165.97462463

900 Cost:  52.9879 
Prediction:
 [[ 157.6585083 ]
 [ 184.64826965]
 [ 184.69551086]
 [ 198.05789185]
 [ 142.1492157 ]
 [  99.42559814]
 [ 144.98431396]
 [ 103.06548309]
 [ 167.64656067]
 [ 147.98997498]]
910 Cost:  52.528 
Prediction:
 [[ 157.63414001]
 [ 184.65675354]
 [ 184.68292236]
 [ 198.0622406 ]
 [ 142.15016174]
 [  99.45857239]
 [ 145.00386047]
 [ 103.10161591]
 [ 167.68528748]
 [ 148.06915283]]
920 Cost:  52.0724 
Prediction:
 [[ 157.60992432]
 [ 184.66514587]
 [ 184.67037964]
 [ 198.0665741 ]
 [ 142.15106201]
 [  99.49138641]
 [ 145.02331543]
 [ 103.13761902]
 [ 167.72381592]
 [ 148.147995  ]]
930 Cost:  51.6212 
Prediction:
 [[ 157.58580017]
 [ 184.67349243]
 [ 184.65791321]
 [ 198.07090759]
 [ 142.15193176]
 [  99.52402496]
 [ 145.04272461]
 [ 103.17350006]
 [ 167.76217651]
 [ 148.22644043]]
940 Cost:  51.1742 
Prediction:
 [[ 157.56181335]
 [ 184.68177795]
 [ 184.64547729]
 [ 198.07516479]
 [ 142.15275574]
 [  99.5565033 ]
 [ 145.06204224]
 [ 103.20923615]
 [ 167.80032349]

1350 Cost:  36.0532 
Prediction:
 [[ 156.67663574]
 [ 184.97808838]
 [ 184.18156433]
 [ 198.23887634]
 [ 142.16490173]
 [ 100.75681305]
 [ 145.79797363]
 [ 104.57210541]
 [ 169.2102356 ]
 [ 151.21092224]]
1360 Cost:  35.7527 
Prediction:
 [[ 156.65730286]
 [ 184.98434448]
 [ 184.17131042]
 [ 198.24258423]
 [ 142.16471863]
 [ 100.78308868]
 [ 145.81462097]
 [ 104.60296631]
 [ 169.24110413]
 [ 151.27508545]]
1370 Cost:  35.4551 
Prediction:
 [[ 156.63806152]
 [ 184.99055481]
 [ 184.16108704]
 [ 198.24629211]
 [ 142.16452026]
 [ 100.80924225]
 [ 145.83123779]
 [ 104.63372803]
 [ 169.27183533]
 [ 151.33894348]]
1380 Cost:  35.1603 
Prediction:
 [[ 156.61889648]
 [ 184.99667358]
 [ 184.15087891]
 [ 198.24993896]
 [ 142.16427612]
 [ 100.83525848]
 [ 145.84773254]
 [ 104.66437531]
 [ 169.30238342]
 [ 151.40248108]]
1390 Cost:  34.8683 
Prediction:
 [[ 156.59986877]
 [ 185.00280762]
 [ 184.14076233]
 [ 198.25361633]
 [ 142.16401672]
 [ 100.86115265]
 [ 145.86421204]
 [ 104.69491577]
 [ 169.332

1830 Cost:  24.4094 
Prediction:
 [[ 155.85246277]
 [ 185.23275757]
 [ 183.73764038]
 [ 198.40298462]
 [ 142.13430786]
 [ 101.87919617]
 [ 146.53471375]
 [ 105.93966675]
 [ 170.5284729 ]
 [ 153.97499084]]
1840 Cost:  24.2187 
Prediction:
 [[ 155.8374176 ]
 [ 185.23716736]
 [ 183.72937012]
 [ 198.40612793]
 [ 142.13327026]
 [ 101.89978027]
 [ 146.54879761]
 [ 105.96582794]
 [ 170.55265808]
 [ 154.0262146 ]]
1850 Cost:  24.0298 
Prediction:
 [[ 155.82240295]
 [ 185.24154663]
 [ 183.72114563]
 [ 198.40924072]
 [ 142.13220215]
 [ 101.92024994]
 [ 146.56282043]
 [ 105.99189758]
 [ 170.57670593]
 [ 154.07719421]]
1860 Cost:  23.8428 
Prediction:
 [[ 155.80749512]
 [ 185.24589539]
 [ 183.71296692]
 [ 198.41238403]
 [ 142.13113403]
 [ 101.94062042]
 [ 146.57679749]
 [ 106.01786804]
 [ 170.60063171]
 [ 154.12794495]]
1870 Cost:  23.6574 
Prediction:
 [[ 155.79266357]
 [ 185.25021362]
 [ 183.70483398]
 [ 198.41549683]
 [ 142.13005066]
 [ 101.96089935]
 [ 146.59072876]
 [ 106.04377747]
 [ 170.624