## Using Matrix

In [16]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  48855.1 
Prediction:
 [[-45.23641205]
 [-50.80394745]
 [-52.04636383]
 [-55.59770966]
 [-38.61835098]]
10 Cost:  1.19474 
Prediction:
 [[ 150.29072571]
 [ 184.20487976]
 [ 179.51199341]
 [ 196.56312561]
 [ 140.63449097]]
20 Cost:  0.747218 
Prediction:
 [[ 150.88244629]
 [ 184.9158783 ]
 [ 180.212677  ]
 [ 197.32577515]
 [ 141.17709351]]
30 Cost:  0.746926 
Prediction:
 [[ 150.8843689 ]
 [ 184.91799927]
 [ 180.21490479]
 [ 197.32778931]
 [ 141.1789856 ]]
40 Cost:  0.746626 
Prediction:
 [[ 150.88450623]
 [ 184.91795349]
 [ 180.21498108]
 [ 197.32748413]
 [ 141.179245  ]]
50 Cost:  0.746345 
Prediction:
 [[ 150.88461304]
 [ 184.91790771]
 [ 180.21507263]
 [ 197.32717896]
 [ 141.17948914]]
60 Cost:  0.746043 
Prediction:
 [[ 150.88475037]
 [ 184.91786194]
 [ 180.21516418]
 [ 197.32685852]
 [ 141.17973328]]
70 Cost:  0.74576 
Prediction:
 [[ 150.8848877 ]
 [ 184.91783142]
 [ 180.21525574]
 [ 197.32658386]
 [ 141.17999268]]
80 Cost:  0.745471 
Prediction:
 [[ 150.88499451]
 [ 184.

880 Cost:  0.722686 
Prediction:
 [[ 150.8952179 ]
 [ 184.91369629]
 [ 180.22219849]
 [ 197.30204773]
 [ 141.19953918]]
890 Cost:  0.722413 
Prediction:
 [[ 150.89533997]
 [ 184.91365051]
 [ 180.22229004]
 [ 197.30175781]
 [ 141.19978333]]
900 Cost:  0.722132 
Prediction:
 [[ 150.89547729]
 [ 184.91358948]
 [ 180.22236633]
 [ 197.3014679 ]
 [ 141.20002747]]
910 Cost:  0.721845 
Prediction:
 [[ 150.89561462]
 [ 184.91355896]
 [ 180.22247314]
 [ 197.30116272]
 [ 141.20027161]]
920 Cost:  0.721575 
Prediction:
 [[ 150.89572144]
 [ 184.91348267]
 [ 180.22254944]
 [ 197.30085754]
 [ 141.20050049]]
930 Cost:  0.7213 
Prediction:
 [[ 150.89585876]
 [ 184.91343689]
 [ 180.22264099]
 [ 197.30056763]
 [ 141.20072937]]
940 Cost:  0.721016 
Prediction:
 [[ 150.89599609]
 [ 184.91337585]
 [ 180.22271729]
 [ 197.30026245]
 [ 141.20095825]]
950 Cost:  0.720737 
Prediction:
 [[ 150.89613342]
 [ 184.91333008]
 [ 180.22280884]
 [ 197.29997253]
 [ 141.20120239]]
960 Cost:  0.72047 
Prediction:
 [[ 150.89

1800 Cost:  0.697581 
Prediction:
 [[ 150.90740967]
 [ 184.90866089]
 [ 180.23016357]
 [ 197.27496338]
 [ 141.22070312]]
1810 Cost:  0.697324 
Prediction:
 [[ 150.90753174]
 [ 184.90861511]
 [ 180.23025513]
 [ 197.27467346]
 [ 141.22091675]]
1820 Cost:  0.697046 
Prediction:
 [[ 150.90766907]
 [ 184.90855408]
 [ 180.23033142]
 [ 197.27436829]
 [ 141.22114563]]
1830 Cost:  0.696776 
Prediction:
 [[ 150.9078064 ]
 [ 184.9085083 ]
 [ 180.23040771]
 [ 197.27407837]
 [ 141.22137451]]
1840 Cost:  0.696518 
Prediction:
 [[ 150.90792847]
 [ 184.90843201]
 [ 180.23048401]
 [ 197.27378845]
 [ 141.22158813]]
1850 Cost:  0.696251 
Prediction:
 [[ 150.9080658 ]
 [ 184.90838623]
 [ 180.23059082]
 [ 197.27349854]
 [ 141.22181702]]
1860 Cost:  0.695982 
Prediction:
 [[ 150.90820312]
 [ 184.9083252 ]
 [ 180.23068237]
 [ 197.27320862]
 [ 141.2220459 ]]
1870 Cost:  0.695725 
Prediction:
 [[ 150.90834045]
 [ 184.90827942]
 [ 180.23075867]
 [ 197.27293396]
 [ 141.22225952]]
1880 Cost:  0.695445 
Prediction