## Numpy Tutorial

In [2]:
import numpy as np

In [5]:
# Numpy array
array_1d = np.array({1,2,3,4,5,6})
print(array_1d)

{1, 2, 3, 4, 5, 6}


In [10]:
array_2d_int = np.array([(1, 2), (3, 4)])
print(array_2d_int)

[[1 2]
 [3 4]]


In [9]:
array_2d_float = np.array([(1, 2), (3, 4)], dtype=float)
print(array_2d_float)

[[ 1.  2.]
 [ 3.  4.]]


In [14]:
zeros_3X4 = np.zeros((3, 4))
print(zeros_3X4)
zeros_3X4 = np.ones((3, 4), dtype=int)
print(zeros_3X4)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
np.arange(14, 35, 5)

array([14, 19, 24, 29, 34])

In [19]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
np.random.random((2, 2))
np.empty((3, 3)) #0보다 약간 작은 값을 넣어줌

array([[  1.28822975e-231,  -1.49457269e-154,   1.83187586e-076],
       [  4.11984965e-033,   7.41043499e-038,   2.32035054e+077],
       [ -2.32035113e+077,   2.32035113e+077,   2.19627342e-314]])

## Inspecting Array

In [37]:
a = np.array([(1, 3), (0.5, 3)])
len(a)
a.size # 갯수
a.dtype
a.astype(int) # 형변환
np.info(a) # 배열정보
a.shape

class:  ndarray
shape:  (2, 2)
strides:  (16, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7f9c2cd2ac30
byteorder:  little
byteswap:  False
type: float64


(2, 2)

## Array Mathematics

In [38]:
e = np.eye(2)
np.dot(e, a)

array([[ 1. ,  3. ],
       [ 0.5,  3. ]])

In [46]:
a = np.array((1, 2, 3))
b = np.array([(1, 2, 3), (4, 5, 6)])

In [50]:
np.vstack((a, b))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])